import React, { createContext, useContext, useState, ReactNode } from 'react';

type SupportedLanguage = 'en' | 'hi' | 'es' | 'fr' | 'de' | 'pt' | 'bn' | 'ta' | 'te' | 'mr' | 'pa' | 'gu';

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  getLanguageName: (code: SupportedLanguage) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const languageNames: Record<SupportedLanguage, string> = {
  en: 'English',
  hi: 'हिंदी (Hindi)',
  es: 'Español (Spanish)',
  fr: 'Français (French)',
  de: 'Deutsch (German)',
  pt: 'Português (Portuguese)',
  bn: 'বাংলা (Bengali)',
  ta: 'தமிழ் (Tamil)',
  te: 'తెలుగు (Telugu)',
  mr: 'मराठी (Marathi)',
  pa: 'ਪੰਜਾਬੀ (Punjabi)',
  gu: 'ગુજરાતી (Gujarati)'
};

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.upload': 'Upload Image',
    'nav.problem': 'Problem Statement',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    
    // Authentication
    'auth.signup.title': 'Create Account',
    'auth.signup.subtitle': 'Join thousands of farmers using AI for crop health',
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Sign in to continue monitoring your crops',
    'auth.name': 'Full Name',
    'auth.email': 'Email Address',
    'auth.phone': 'Phone Number',
    'auth.password': 'Password',
    'auth.language': 'Preferred Language',
    'auth.english': 'English',
    'auth.hindi': 'हिंदी',
    'auth.signup.button': 'Create Account',
    'auth.login.button': 'Sign In',
    'auth.signup.link': "Don't have an account? Sign up",
    'auth.login.link': 'Already have an account? Sign in',
    
    // Home page
    'home.title': 'AI-Powered Plant Health Detection',
    'home.subtitle': 'Protect your crops with instant disease and nutrient deficiency diagnosis',
    'home.cta': 'Start Diagnosis',
    'home.stat.title': 'Critical Agricultural Challenge',
    'home.stat.description': 'of global food production is lost annually due to plant diseases and nutrient deficiencies',
    'home.stat.source': 'Source: Food and Agriculture Organization (FAO)',
    'home.howit.title': 'How It Works',
    'home.howit.step1.title': 'Upload Image',
    'home.howit.step1.desc': 'Capture or upload a photo of the affected plant leaf',
    'home.howit.step2.title': 'AI Analysis',
    'home.howit.step2.desc': 'Our advanced AI analyzes the image for diseases and deficiencies',
    'home.howit.step3.title': 'Get Treatment',
    'home.howit.step3.desc': 'Receive instant diagnosis and treatment recommendations',
    
    // Upload page
    'upload.title': 'Upload Plant Image',
    'upload.subtitle': 'Get instant AI-powered diagnosis of your plant health',
    'upload.dragdrop': 'Drag and drop your plant image here, or',
    'upload.browse': 'browse files',
    'upload.camera': 'Take Photo',
    'upload.supported': 'Supported: JPG, PNG, WebP (max 5MB)',
    'upload.analyze': 'Analyze Image',
    'upload.analyzing': 'Analyzing...',
    'upload.results.title': 'Diagnosis Results',
    'upload.results.disease': 'Detected Disease',
    'upload.results.confidence': 'Confidence',
    'upload.results.treatment': 'Recommended Treatment',
    'upload.results.retry': 'Upload Another Image',
    
    // Problem Statement page
    'problem.title': 'Agricultural Challenges',
    'problem.subtitle': 'Understanding the critical need for AI-powered plant health monitoring',
    'problem.intro': 'Agriculture faces significant losses due to late or inaccurate detection of plant diseases and nutrient deficiencies, with the FAO estimating that 20–40% of global food production is lost annually.',
    'problem.section1.title': 'The Scale of the Problem',
    'problem.section1.content': 'In countries like India, over 35% of crop yield is destroyed every year by pests and diseases. Farmers in developing regions largely depend on manual inspection, which is not only subjective and error-prone but also requires expert knowledge that is often inaccessible.',
    'problem.section2.title': 'Nutrient Deficiency Impact',
    'problem.section2.content': 'Nutrient deficiencies such as nitrogen (N), phosphorus (P), potassium (K), calcium (Ca), and iron (Fe) further limit crop growth, leading to reduced productivity and threatening food security.',
    'problem.section3.title': 'Traditional Methods Limitations',
    'problem.section3.content': 'Traditional diagnostic methods, such as laboratory-based soil or tissue analysis, are expensive, time-consuming, and impractical for small-scale farmers.',
    'problem.section4.title': 'AI-Powered Solution',
    'problem.section4.content': 'Recent advances in deep learning and computer vision have shown great promise in overcoming these limitations. Studies demonstrate that models like CNN, DenseNet, MobileNet, and InceptionResNet can classify plant diseases and nutrient deficiencies with accuracies exceeding 90%, often outperforming human experts.',
    'problem.conclusion': 'This project proposes the development of a GenAI-based plant health monitoring system that leverages plant leaf image datasets and state-of-the-art deep learning models. The system will be deployed as a lightweight web and mobile application, enabling farmers to diagnose plant diseases and nutrient deficiencies in real time by simply capturing leaf images with their device.',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.continue': 'Continue',
    'auth.voice.label': 'Use Voice Input',
    'auth.voice.listening': 'Listening...',
    'auth.voice.speak': 'Speak now',
    'auth.voice.stop': 'Stop listening',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.upload': 'छवि अपलोड करें',
    'nav.problem': 'समस्या विवरण',
    'nav.logout': 'लॉगआउट',
    'nav.login': 'लॉगिन',
    'nav.signup': 'साइन अप',
    
    // Authentication
    'auth.signup.title': 'खाता बनाएं',
    'auth.signup.subtitle': 'फसल स्वास्थ्य के लिए AI का उपयोग करने वाले हजारों किसानों से जुड़ें',
    'auth.login.title': 'वापस आपका स्वागत है',
    'auth.login.subtitle': 'अपनी फसलों की निगरानी जारी रखने के लिए साइन इन करें',
    'auth.name': 'पूरा नाम',
    'auth.email': 'ईमेल पता',
    'auth.phone': 'फोन नंबर',
    'auth.password': 'पासवर्ड',
    'auth.language': 'पसंदीदा भाषा',
    'auth.english': 'English',
    'auth.hindi': 'हिंदी',
    'auth.signup.button': 'खाता बनाएं',
    'auth.login.button': 'साइन इन करें',
    'auth.signup.link': 'खाता नहीं है? साइन अप करें',
    'auth.login.link': 'पहले से खाता है? साइन इन करें',
    
    // Home page
    'home.title': 'AI-संचालित पौधे स्वास्थ्य निदान',
    'home.subtitle': 'तत्काल रोग और पोषक तत्व की कमी निदान के साथ अपनी फसलों की सुरक्षा करें',
    'home.cta': 'निदान शुरू करें',
    'home.stat.title': 'महत्वपूर्ण कृषि चुनौती',
    'home.stat.description': 'वैश्विक खाद्य उत्पादन का हिस्सा पौधों की बीमारियों और पोषक तत्वों की कमी के कारण हर साल नष्ट हो जाता है',
    'home.stat.source': 'स्रोत: खाद्य और कृषि संगठन (FAO)',
    'home.howit.title': 'यह कैसे काम करता है',
    'home.howit.step1.title': 'छवि अपलोड करें',
    'home.howit.step1.desc': 'प्रभावित पौधे की पत्ती की तस्वीर लें या अपलोड करें',
    'home.howit.step2.title': 'AI विश्लेषण',
    'home.howit.step2.desc': 'हमारा उन्नत AI रोगों और कमियों के लिए छवि का विश्लेषण करता है',
    'home.howit.step3.title': 'इलाज प्राप्त करें',
    'home.howit.step3.desc': 'तत्काल निदान और उपचार की सिफारिशें प्राप्त करें',
    
    // Upload page
    'upload.title': 'पौधे की छवि अपलोड करें',
    'upload.subtitle': 'अपने पौधे के स्वास्थ्य का तत्काल AI-संचालित निदान प्राप्त करें',
    'upload.dragdrop': 'अपने पौधे की छवि यहाँ ड्रैग और ड्रॉप करें, या',
    'upload.browse': 'फाइलें ब्राउज़ करें',
    'upload.camera': 'फोटो लें',
    'upload.supported': 'समर्थित: JPG, PNG, WebP (अधिकतम 5MB)',
    'upload.analyze': 'छवि का विश्लेषण करें',
    'upload.analyzing': 'विश्लेषण कर रहे हैं...',
    'upload.results.title': 'निदान परिणाम',
    'upload.results.disease': 'पहचानी गई बीमारी',
    'upload.results.confidence': 'विश्वास',
    'upload.results.treatment': 'अनुशंसित उपचार',
    'upload.results.retry': 'दूसरी छवि अपलोड करें',
    
    // Problem Statement page
    'problem.title': 'कृषि चुनौतियां',
    'problem.subtitle': 'AI-संचालित पौधे स्वास्थ्य निगरानी की महत्वपूर्ण आवश्यकता को समझना',
    'problem.intro': 'पौधों की बीमारियों और पोषक तत्वों की कमी की देर से या गलत पहचान के कारण कृषि को महत्वपूर्ण नुकसान होते हैं, FAO का अनुमान है कि वैश्विक खाद्य उत्पादन का 20-40% हर साल नष्ट हो जाता है।',
    'problem.section1.title': 'समस्या का पैमाना',
    'problem.section1.content': 'भारत जैसे देशों में, हर साल 35% से अधिक फसल की पैदावार कीटों और बीमारियों से नष्ट हो जाती है। विकासशील क्षेत्रों के किसान बड़े पैमाने पर मैनुअल निरीक्षण पर निर्भर करते हैं, जो न केवल व्यक्तिपरक और त्रुटि-प्रवण है बल्कि विशेषज्ञ ज्ञान की आवश्यकता होती है जो अक्सर पहुंच से बाहर होती है।',
    'problem.section2.title': 'पोषक तत्व की कमी का प्रभाव',
    'problem.section2.content': 'नाइट्रोजन (N), फास्फोरस (P), पोटेशियम (K), कैल्शियम (Ca), और आयरन (Fe) जैसे पोषक तत्वों की कमी फसल की वृद्धि को और सीमित करती है, जिससे उत्पादकता में कमी आती है और खाद्य सुरक्षा को खतरा होता है।',
    'problem.section3.title': 'पारंपरिक विधियों की सीमाएं',
    'problem.section3.content': 'पारंपरिक निदान विधियां, जैसे कि प्रयोगशाला-आधारित मिट्टी या ऊतक विश्लेषण, महंगे, समय लगाने वाले और छोटे पैमाने के किसानों के लिए अव्यावहारिक हैं।',
    'problem.section4.title': 'AI-संचालित समाधान',
    'problem.section4.content': 'गहन शिक्षा और कंप्यूटर दृष्टि में हाल की प्रगति ने इन सीमाओं को पार करने में बहुत आशाजनक संभावनाएं दिखाई हैं। अध्ययन दिखाते हैं कि CNN, DenseNet, MobileNet, और InceptionResNet जैसे मॉडल 90% से अधिक सटीकता के साथ पौधों की बीमारियों और पोषक तत्वों की कमी को वर्गीकृत कर सकते हैं, अक्सर मानव विशेषज्ञों से बेहतर प्रदर्शन करते हैं।',
    'problem.conclusion': 'यह परियोजना एक GenAI-आधारित पौधे स्वास्थ्य निगरानी प्रणाली के विकास का प्रस्ताव करती है जो पौधे की पत्ती छवि डेटासेट और अत्याधुनिक गहन शिक्षा मॉडल का लाभ उठाती है। प्रणाली को एक हल्के वेब और मोबाइल एप्लिकेशन के रूप में तैनात किया जाएगा, जो किसानों को केवल अपने डिवाइस के साथ पत्ती की छवियों को कैप्चर करके वास्तविक समय में पौधों की बीमारियों और पोषक तत्वों की कमी का निदान करने में सक्षम बनाएगा।',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'एक त्रुटि हुई',
    'common.success': 'सफलता',
    'common.cancel': 'रद्द करें',
    'common.continue': 'जारी रखें',
    'auth.voice.label': 'आवाज इनपुट का उपयोग करें',
    'auth.voice.listening': 'सुन रहे हैं...',
    'auth.voice.speak': 'अब बोलें',
    'auth.voice.stop': 'सुनना बंद करें',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.upload': 'Subir Imagen',
    'nav.problem': 'Declaración del Problema',
    'nav.logout': 'Cerrar Sesión',
    'nav.login': 'Iniciar Sesión',
    'nav.signup': 'Registrarse',
    'auth.signup.title': 'Crear Cuenta',
    'auth.signup.subtitle': 'Únete a miles de agricultores usando IA para la salud de los cultivos',
    'auth.login.title': 'Bienvenido de Nuevo',
    'auth.login.subtitle': 'Inicia sesión para continuar monitoreando tus cultivos',
    'auth.name': 'Nombre Completo',
    'auth.email': 'Correo Electrónico',
    'auth.phone': 'Número de Teléfono',
    'auth.password': 'Contraseña',
    'auth.language': 'Idioma Preferido',
    'auth.signup.button': 'Crear Cuenta',
    'auth.login.button': 'Iniciar Sesión',
    'auth.signup.link': '¿No tienes cuenta? Regístrate',
    'auth.login.link': '¿Ya tienes cuenta? Inicia sesión',
    'home.title': 'Detección de Salud Vegetal con IA',
    'home.subtitle': 'Protege tus cultivos con diagnóstico instantáneo de enfermedades y deficiencias nutricionales',
    'home.cta': 'Iniciar Diagnóstico',
    'common.loading': 'Cargando...',
    'common.error': 'Ocurrió un error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.continue': 'Continuar',
    'auth.voice.label': 'Usar Entrada de Voz',
    'auth.voice.listening': 'Escuchando...',
    'auth.voice.speak': 'Habla ahora',
    'auth.voice.stop': 'Dejar de escuchar',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.upload': 'Télécharger Image',
    'nav.problem': 'Énoncé du Problème',
    'nav.logout': 'Déconnexion',
    'nav.login': 'Connexion',
    'nav.signup': "S'inscrire",
    'auth.signup.title': 'Créer un Compte',
    'auth.signup.subtitle': 'Rejoignez des milliers d\'agriculteurs utilisant l\'IA pour la santé des cultures',
    'auth.login.title': 'Bon Retour',
    'auth.login.subtitle': 'Connectez-vous pour continuer à surveiller vos cultures',
    'auth.name': 'Nom Complet',
    'auth.email': 'Adresse Email',
    'auth.phone': 'Numéro de Téléphone',
    'auth.password': 'Mot de Passe',
    'auth.language': 'Langue Préférée',
    'auth.signup.button': 'Créer un Compte',
    'auth.login.button': 'Se Connecter',
    'auth.signup.link': 'Pas de compte? Inscrivez-vous',
    'auth.login.link': 'Déjà un compte? Connectez-vous',
    'home.title': 'Détection de Santé des Plantes par IA',
    'home.subtitle': 'Protégez vos cultures avec un diagnostic instantané des maladies et carences nutritionnelles',
    'home.cta': 'Commencer le Diagnostic',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur s\'est produite',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.continue': 'Continuer',
    'auth.voice.label': 'Utiliser l\'Entrée Vocale',
    'auth.voice.listening': 'Écoute en cours...',
    'auth.voice.speak': 'Parlez maintenant',
    'auth.voice.stop': 'Arrêter d\'écouter',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.upload': 'Bild Hochladen',
    'nav.problem': 'Problembeschreibung',
    'nav.logout': 'Abmelden',
    'nav.login': 'Anmelden',
    'nav.signup': 'Registrieren',
    'auth.signup.title': 'Konto Erstellen',
    'auth.signup.subtitle': 'Schließen Sie sich Tausenden von Landwirten an, die KI für die Pflanzengesundheit nutzen',
    'auth.login.title': 'Willkommen Zurück',
    'auth.login.subtitle': 'Melden Sie sich an, um Ihre Pflanzen weiter zu überwachen',
    'auth.name': 'Vollständiger Name',
    'auth.email': 'E-Mail-Adresse',
    'auth.phone': 'Telefonnummer',
    'auth.password': 'Passwort',
    'auth.language': 'Bevorzugte Sprache',
    'auth.signup.button': 'Konto Erstellen',
    'auth.login.button': 'Anmelden',
    'auth.signup.link': 'Noch kein Konto? Registrieren',
    'auth.login.link': 'Bereits ein Konto? Anmelden',
    'home.title': 'KI-gestützte Pflanzengesundheitserkennung',
    'home.subtitle': 'Schützen Sie Ihre Pflanzen mit sofortiger Diagnose von Krankheiten und Nährstoffmängeln',
    'home.cta': 'Diagnose Starten',
    'common.loading': 'Wird geladen...',
    'common.error': 'Ein Fehler ist aufgetreten',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.continue': 'Fortfahren',
    'auth.voice.label': 'Spracheingabe Verwenden',
    'auth.voice.listening': 'Hört zu...',
    'auth.voice.speak': 'Jetzt sprechen',
    'auth.voice.stop': 'Aufhören zuzuhören',
  },
  pt: {
    'nav.home': 'Início',
    'nav.upload': 'Carregar Imagem',
    'nav.problem': 'Declaração do Problema',
    'nav.logout': 'Sair',
    'nav.login': 'Entrar',
    'nav.signup': 'Cadastrar',
    'auth.signup.title': 'Criar Conta',
    'auth.signup.subtitle': 'Junte-se a milhares de agricultores usando IA para saúde das plantas',
    'auth.login.title': 'Bem-vindo de Volta',
    'auth.login.subtitle': 'Faça login para continuar monitorando suas plantas',
    'auth.name': 'Nome Completo',
    'auth.email': 'Endereço de Email',
    'auth.phone': 'Número de Telefone',
    'auth.password': 'Senha',
    'auth.language': 'Idioma Preferido',
    'auth.signup.button': 'Criar Conta',
    'auth.login.button': 'Entrar',
    'auth.signup.link': 'Não tem conta? Cadastre-se',
    'auth.login.link': 'Já tem conta? Entre',
    'home.title': 'Detecção de Saúde Vegetal com IA',
    'home.subtitle': 'Proteja suas plantas com diagnóstico instantâneo de doenças e deficiências nutricionais',
    'home.cta': 'Iniciar Diagnóstico',
    'common.loading': 'Carregando...',
    'common.error': 'Ocorreu um erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.continue': 'Continuar',
    'auth.voice.label': 'Usar Entrada de Voz',
    'auth.voice.listening': 'Ouvindo...',
    'auth.voice.speak': 'Fale agora',
    'auth.voice.stop': 'Parar de ouvir',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.upload': 'ছবি আপলোড করুন',
    'nav.problem': 'সমস্যা বিবৃতি',
    'nav.logout': 'লগআউট',
    'nav.login': 'লগইন',
    'nav.signup': 'সাইন আপ',
    'auth.signup.title': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.signup.subtitle': 'ফসলের স্বাস্থ্যের জন্য AI ব্যবহার করা হাজার হাজার কৃষকদের সাথে যোগ দিন',
    'auth.login.title': 'আবার স্বাগতম',
    'auth.login.subtitle': 'আপনার ফসল পর্যবেক্ষণ চালিয়ে যেতে সাইন ইন করুন',
    'auth.name': 'পূর্ণ নাম',
    'auth.email': 'ইমেইল ঠিকানা',
    'auth.phone': 'ফোন নম্বর',
    'auth.password': 'পাসওয়ার্ড',
    'auth.language': 'পছন্দের ভাষা',
    'auth.signup.button': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.login.button': 'সাইন ইন করুন',
    'auth.signup.link': 'অ্যাকাউন্ট নেই? সাইন আপ করুন',
    'auth.login.link': 'ইতিমধ্যে অ্যাকাউন্ট আছে? সাইন ইন করুন',
    'home.title': 'AI-চালিত উদ্ভিদ স্বাস্থ্য সনাক্তকরণ',
    'home.subtitle': 'তাত্ক্ষণিক রোগ এবং পুষ্টি ঘাটতি নির্ণয়ের মাধ্যমে আপনার ফসল রক্ষা করুন',
    'home.cta': 'নির্ণয় শুরু করুন',
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'একটি ত্রুটি ঘটেছে',
    'common.success': 'সফলতা',
    'common.cancel': 'বাতিল করুন',
    'common.continue': 'চালিয়ে যান',
    'auth.voice.label': 'ভয়েস ইনপুট ব্যবহার করুন',
    'auth.voice.listening': 'শুনছি...',
    'auth.voice.speak': 'এখন বলুন',
    'auth.voice.stop': 'শোনা বন্ধ করুন',
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.upload': 'படம் பதிவேற்றவும்',
    'nav.problem': 'சிக்கல் அறிக்கை',
    'nav.logout': 'வெளியேறு',
    'nav.login': 'உள்நுழை',
    'nav.signup': 'பதிவு செய்க',
    'auth.signup.title': 'கணக்கை உருவாக்கவும்',
    'auth.signup.subtitle': 'பயிர் ஆரோக்கியத்திற்கு AI ஐப் பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் சேரவும்',
    'auth.login.title': 'மீண்டும் வரவேற்கிறோம்',
    'auth.login.subtitle': 'உங்கள் பயிர்களை தொடர்ந்து கண்காணிக்க உள்நுழையவும்',
    'auth.name': 'முழு பெயர்',
    'auth.email': 'மின்னஞ்சல் முகவரி',
    'auth.phone': 'தொலைபேசி எண்',
    'auth.password': 'கடவுச்சொல்',
    'auth.language': 'விருப்பமான மொழி',
    'auth.signup.button': 'கணக்கை உருவாக்கவும்',
    'auth.login.button': 'உள்நுழை',
    'auth.signup.link': 'கணக்கு இல்லையா? பதிவு செய்க',
    'auth.login.link': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழை',
    'home.title': 'AI-இயங்கும் தாவர ஆரோக்கிய கண்டறிதல்',
    'home.subtitle': 'உடனடி நோய் மற்றும் ஊட்டச்சத்து குறைபாடு கண்டறிதலுடன் உங்கள் பயிர்களைப் பாதுகாக்கவும்',
    'home.cta': 'கண்டறிதலை தொடங்கவும்',
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை ஏற்பட்டது',
    'common.success': 'வெற்றி',
    'common.cancel': 'ரத்துசெய்',
    'common.continue': 'தொடர்',
    'auth.voice.label': 'குரல் உள்ளீட்டைப் பயன்படுத்தவும்',
    'auth.voice.listening': 'கேட்கிறது...',
    'auth.voice.speak': 'இப்போது பேசுங்கள்',
    'auth.voice.stop': 'கேட்பதை நிறுத்து',
  },
  te: {
    'nav.home': 'హోమ్',
    'nav.upload': 'చిత్రం అప్‌లోడ్ చేయండి',
    'nav.problem': 'సమస్య ప్రకటన',
    'nav.logout': 'లాగ్అవుట్',
    'nav.login': 'లాగిన్',
    'nav.signup': 'సైన్ అప్',
    'auth.signup.title': 'ఖాతాను సృష్టించండి',
    'auth.signup.subtitle': 'పంట ఆరోగ్యం కోసం AI ఉపయోగిస్తున్న వేలాది రైతులతో చేరండి',
    'auth.login.title': 'తిరిగి స్వాగతం',
    'auth.login.subtitle': 'మీ పంటలను పర్యవేక్షించడం కొనసాగించడానికి సైన్ ఇన్ చేయండి',
    'auth.name': 'పూర్తి పేరు',
    'auth.email': 'ఇమెయిల్ చిరునామా',
    'auth.phone': 'ఫోన్ నంబర్',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.language': 'ఇష్టమైన భాష',
    'auth.signup.button': 'ఖాతాను సృష్టించండి',
    'auth.login.button': 'సైన్ ఇన్',
    'auth.signup.link': 'ఖాతా లేదా? సైన్ అప్ చేయండి',
    'auth.login.link': 'ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి',
    'home.title': 'AI-శక్తితో మొక్క ఆరోగ్య గుర్తింపు',
    'home.subtitle': 'తక్షణ వ్యాధి మరియు పోషక లోపం నిర్ధారణతో మీ పంటలను రక్షించండి',
    'home.cta': 'నిర్ధారణ ప్రారంభించండి',
    'common.loading': 'లోడ్ అవుతోంది...',
    'common.error': 'లోపం సంభవించింది',
    'common.success': 'విజయం',
    'common.cancel': 'రద్దు చేయండి',
    'common.continue': 'కొనసాగించండి',
    'auth.voice.label': 'వాయిస్ ఇన్‌పుట్ ఉపయోగించండి',
    'auth.voice.listening': 'వింటోంది...',
    'auth.voice.speak': 'ఇప్పుడు మాట్లాడండి',
    'auth.voice.stop': 'వినడం ఆపండి',
  },
  mr: {
    'nav.home': 'होम',
    'nav.upload': 'प्रतिमा अपलोड करा',
    'nav.problem': 'समस्या विवरण',
    'nav.logout': 'लॉगआउट',
    'nav.login': 'लॉगिन',
    'nav.signup': 'साइन अप',
    'auth.signup.title': 'खाते तयार करा',
    'auth.signup.subtitle': 'पीक आरोग्यासाठी AI वापरणाऱ्या हजारो शेतकऱ्यांमध्ये सामील व्हा',
    'auth.login.title': 'परत स्वागत आहे',
    'auth.login.subtitle': 'तुमच्या पिकांचे निरीक्षण सुरू ठेवण्यासाठी साइन इन करा',
    'auth.name': 'पूर्ण नाव',
    'auth.email': 'ईमेल पत्ता',
    'auth.phone': 'फोन नंबर',
    'auth.password': 'पासवर्ड',
    'auth.language': 'पसंतीची भाषा',
    'auth.signup.button': 'खाते तयार करा',
    'auth.login.button': 'साइन इन',
    'auth.signup.link': 'खाते नाही? साइन अप करा',
    'auth.login.link': 'आधीपासून खाते आहे? साइन इन करा',
    'home.title': 'AI-चालित वनस्पती आरोग्य शोध',
    'home.subtitle': 'त्वरित रोग आणि पोषक कमतरता निदानासह आपल्या पिकांचे संरक्षण करा',
    'home.cta': 'निदान सुरू करा',
    'common.loading': 'लोड होत आहे...',
    'common.error': 'त्रुटी आली',
    'common.success': 'यश',
    'common.cancel': 'रद्द करा',
    'common.continue': 'सुरू ठेवा',
    'auth.voice.label': 'व्हॉइस इनपुट वापरा',
    'auth.voice.listening': 'ऐकत आहे...',
    'auth.voice.speak': 'आता बोला',
    'auth.voice.stop': 'ऐकणे थांबवा',
  },
  pa: {
    'nav.home': 'ਘਰ',
    'nav.upload': 'ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ',
    'nav.problem': 'ਸਮੱਸਿਆ ਬਿਆਨ',
    'nav.logout': 'ਲਾਗਆਉਟ',
    'nav.login': 'ਲਾਗਇਨ',
    'nav.signup': 'ਸਾਈਨ ਅੱਪ',
    'auth.signup.title': 'ਖਾਤਾ ਬਣਾਓ',
    'auth.signup.subtitle': 'ਫਸਲ ਸਿਹਤ ਲਈ AI ਵਰਤਣ ਵਾਲੇ ਹਜ਼ਾਰਾਂ ਕਿਸਾਨਾਂ ਨਾਲ ਜੁੜੋ',
    'auth.login.title': 'ਵਾਪਸ ਜੀ ਆਇਆਂ ਨੂੰ',
    'auth.login.subtitle': 'ਆਪਣੀਆਂ ਫਸਲਾਂ ਦੀ ਨਿਗਰਾਨੀ ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ',
    'auth.name': 'ਪੂਰਾ ਨਾਮ',
    'auth.email': 'ਈਮੇਲ ਪਤਾ',
    'auth.phone': 'ਫੋਨ ਨੰਬਰ',
    'auth.password': 'ਪਾਸਵਰਡ',
    'auth.language': 'ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ',
    'auth.signup.button': 'ਖਾਤਾ ਬਣਾਓ',
    'auth.login.button': 'ਸਾਈਨ ਇਨ',
    'auth.signup.link': 'ਖਾਤਾ ਨਹੀਂ ਹੈ? ਸਾਈਨ ਅੱਪ ਕਰੋ',
    'auth.login.link': 'ਪਹਿਲਾਂ ਤੋਂ ਹੀ ਖਾਤਾ ਹੈ? ਸਾਈਨ ਇਨ ਕਰੋ',
    'home.title': 'AI-ਸੰਚਾਲਿਤ ਪੌਦਾ ਸਿਹਤ ਖੋਜ',
    'home.subtitle': 'ਤੁਰੰਤ ਬੀਮਾਰੀ ਅਤੇ ਪੋਸ਼ਣ ਦੀ ਕਮੀ ਦੇ ਨਿਦਾਨ ਨਾਲ ਆਪਣੀਆਂ ਫਸਲਾਂ ਦੀ ਰੱਖਿਆ ਕਰੋ',
    'home.cta': 'ਨਿਦਾਨ ਸ਼ੁਰੂ ਕਰੋ',
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'common.error': 'ਇੱਕ ਗਲਤੀ ਆਈ',
    'common.success': 'ਸਫਲਤਾ',
    'common.cancel': 'ਰੱਦ ਕਰੋ',
    'common.continue': 'ਜਾਰੀ ਰੱਖੋ',
    'auth.voice.label': 'ਵੌਇਸ ਇਨਪੁੱਟ ਵਰਤੋ',
    'auth.voice.listening': 'ਸੁਣ ਰਿਹਾ ਹੈ...',
    'auth.voice.speak': 'ਹੁਣ ਬੋਲੋ',
    'auth.voice.stop': 'ਸੁਣਨਾ ਬੰਦ ਕਰੋ',
  },
  gu: {
    'nav.home': 'હોમ',
    'nav.upload': 'છબી અપલોડ કરો',
    'nav.problem': 'સમસ્યા નિવેદન',
    'nav.logout': 'લૉગઆઉટ',
    'nav.login': 'લૉગિન',
    'nav.signup': 'સાઇન અપ',
    'auth.signup.title': 'ખાતું બનાવો',
    'auth.signup.subtitle': 'પાક સ્વાસ્થ્ય માટે AI નો ઉપયોગ કરતા હજારો ખેડૂતો સાથે જોડાઓ',
    'auth.login.title': 'પાછા સ્વાગત છે',
    'auth.login.subtitle': 'તમારા પાકોનું નિરીક્ષણ ચાલુ રાખવા માટે સાઇન ઇન કરો',
    'auth.name': 'સંપૂર્ણ નામ',
    'auth.email': 'ઇમેઇલ સરનામું',
    'auth.phone': 'ફોન નંબર',
    'auth.password': 'પાસવર્ડ',
    'auth.language': 'પસંદગીની ભાષા',
    'auth.signup.button': 'ખાતું બનાવો',
    'auth.login.button': 'સાઇન ઇન',
    'auth.signup.link': 'ખાતું નથી? સાઇન અપ કરો',
    'auth.login.link': 'પહેલેથી જ ખાતું છે? સાઇન ઇન કરો',
    'home.title': 'AI-સંચાલિત છોડ સ્વાસ્થ્ય શોધ',
    'home.subtitle': 'તાત્કાલિક રોગ અને પોષણ ઉણપના નિદાન સાથે તમારા પાકોનું રક્ષણ કરો',
    'home.cta': 'નિદાન શરૂ કરો',
    'common.loading': 'લોડ થઈ રહ્યું છે...',
    'common.error': 'એક ભૂલ આવી',
    'common.success': 'સફળતા',
    'common.cancel': 'રદ કરો',
    'common.continue': 'ચાલુ રાખો',
    'auth.voice.label': 'વૉઇસ ઇનપુટ વાપરો',
    'auth.voice.listening': 'સાંભળી રહ્યાં છીએ...',
    'auth.voice.speak': 'હવે બોલો',
    'auth.voice.stop': 'સાંભળવાનું બંધ કરો',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<SupportedLanguage>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const getLanguageName = (code: SupportedLanguage): string => {
    return languageNames[code];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLanguageName }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}